### ISSUE TITLE
build-gradle doesn't like spaces in paths

### ISSUE THREAD

**Issue by chefhoobajoob** [AtomBuild/atom-build-gradle#10]
One of the folders in the path leading to my gradle wrapper file is named `Visual Studio 2013`, and this causes `atom-build-gradle` to stumble. It's likely just an embedded quotes problem:

```
Ooops. Something went wrong.
Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat tasks"
'C:\Users\hoobajoob\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat tasks"
'C:\Users\hoobajoob\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by chefhoobajoob** [comment]
I can work around it with this change on line 81 of `gradle.js`:

```
executable = '"' + path.join(this.cwd, wrapperFile) + '"';
```

**Comment by noseglid** [comment]
It's weird that it is not working. It looks as it is properly quoted in your output:

```
C:\Windows\system32\cmd.exe /s /c "C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat tasks"
```

If you copy that line into your prompt, does it work?

**Comment by chefhoobajoob** [comment]
No, it needs to be like so:

```
C:\Windows\system32\cmd.exe /s /c ""C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat" tasks"
```

See [here](http://stackoverflow.com/questions/6376113/spaces-problem-in-cmd) for reference.

**Comment by noseglid** [comment]
Is this still an issue since `build` switch to `cross-spawn-async` ?

**Comment by ThePhilderbeast** [comment]
just did a source download, this is still an issue.

**Comment by ThePhilderbeast** [comment]
I have some workling code on windows

I have changed the last line of the below snippet and it now works however im fairly certain this wont work on non-windows.

`const wrapperFile = /^win/.test(process.platform) ? 'gradlew.bat' : 'gradlew';
      let executable;
      return statAsync(path.join(this.cwd, wrapperFile)).then(() => {
        executable = path.join(this.cwd, wrapperFile);
      }).catch(err => {
        executable = 'gradle';
      }).then(() => {
            return execAsync('"' + executable + '" tasks', { cwd: this.cwd });`
