### ISSUE TITLE
Does not run gradlew.bat on windows systems

### ISSUE THREAD

**Issue by chefhoobajoob** [AtomBuild/atom-build-gradle#5]
New to Atom and atom-build-gradle. Not new to gradle. I'm running Atom 1.2.3, and have installed language-groovy, language-gradle, atom-build, and atom-build-gradle.

Why aren't there some basic instructions on the repo for how to run gradle tasks with this package? So far, the only thing I can see that it has done is determined how many tasks are available from my build.gradle setup.

Now what? There are literally no context menus or any other place I can find to run gradle tasks.

**Comment by chefhoobajoob** [comment]
Ok, am I right in thinking that I need to refer to atom-build to figure out how to use this tool?

If so, I can't seem to figure out how to configure it to run what I want it to run. `ctrl-alt-t` gets me a gradle task list, but when I choose a task, it decides it wants to use `gradlew` instead of `gradlew.bat` to run the task, which obviously fails on my Windows system.

So, how do I control what it's doing? How can I get it to run `gradlew.bat`?

**Comment by chefhoobajoob** [comment]
So far, the only thing I've been able to do is edit gradle.js to use `gradlew.bat` instead of `gradlew`.

Seems like a defect, though.

**Comment by noseglid** [comment]
Sorry for taking so long to respond.
I think we should check which OS we're running on, similar to how it is [done in the gulp provider](https://github.com/AtomBuild/atom-build-gulp/blob/master/lib/gulp.js#L38).

**Comment by chefhoobajoob** [comment]
Agreed

**Comment by noseglid** [comment]
I have a proposed solution pushed to #8. I have no windows machine so I can't test it. Can you verify if this is enough?

**Comment by chefhoobajoob** [comment]
Sure

**Comment by chefhoobajoob** [comment]
Not sure if I updated correctly. I just grabbed the modified lines from your commit rather than the whole file. This is the revised code on my machine now:

``` javascript
    settings: function (cwd) {
      let wrapperFile = /^win/.test(process.platform) ? 'gradlew.bat' : 'gradlew';
      let executable;
      return statAsync(path.join(this.cwd, wrapperFile)).then(() => {
        executable = path.join(this.cwd, wrapperFile);
      }).catch(function (err) {
        executable = 'gradle';
      }).then(() => {
        return execAsync(executable + ' tasks', { cwd: cwd });
      }).then((outputBuffer) => {
        const lineContext = {
          state: 'idle'
        };
        return outputBuffer
          .toString('utf8')
          .split(os.EOL)
          .map(lineToTask.bind(lineContext))
          .filter(isFalsy)
          .map(taskToConfig.bind(null, executable));
      });
    },
```

...and when I restarted Atom, I got an error loading the plugin:

```
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.settings (C:/Users/jamesm/.atom/packages/build-gradle/lib/gradle.js:66:29)
    at C:/Users/jamesm/.atom/packages/build/lib/build.js:207:32
```

...I think whatever that /^win/.test(process.platform) does on your system, it doesn't do on mine.

``` javascript
      let wrapperFile = /^win/.test(process.platform) ? 'gradlew.bat' : 'gradlew';
```

**Comment by noseglid** [comment]
That's standard javascript. There should be no issue doing that on windows.

Uninstall `build-gradle`, then do this:
- Clone this repository
- Checkout branch `windows`
- Run `apm install` in that folder
- Run `apm link`
- Restart Atom

**Comment by chefhoobajoob** [comment]
oh - I'm not set up for git on my windows machine - that's why I modified it in place. I can get it set up, but it might be a while before I can get back to you.

**Comment by noseglid** [comment]
There's no rush. Let me know when you've had time to try it out.

**Comment by chefhoobajoob** [comment]
Got my git setup in place - hope to get to this today

**Comment by chefhoobajoob** [comment]
Hm - you might have to help me out here - I'm pretty `apm` ignorant. I cloned the repository and checked out the windows branch.

`apm install` completed successfully, but `apm link`, run from the same folder as `apm install`, gives me this error:

```
Linking C:\Users\hoobajoob\.atom\packages\build-gradle to
C:\Users\hoobajoob\Documents\GitHub\atom-build-gradle failed:
EEXIST, file already exists
'C:\Users\hoobajoob\Documents\GitHub\atom-build-gradle'
```

**Comment by chefhoobajoob** [comment]
I think the change you made on the windows branch is working.

I tried moving the as-is `.atom/packages/build-gradle` contents on my system to another folder and adding a shortcut in `.atom/packages` to link to the cloned repo, but restarting atom after that behaved poorly: `ctrl+alt+t` on the project claimed there were no targets available.

I then tried copying the repo contents directly into `.atom/packages/build-gradle`, rather than using the shortcut, and apparently the `node_modules` folder contains a deep enough structure that I ran into Windows' moronic `path too long` error, and couldn't copy everything over.

I tried starting Atom anyway, and it ran no problem: `ctrl+alt+t` gave me the list of targets, and selecting `build` successfully ran `gradlew.bat`

**Comment by noseglid** [comment]
So you're process looks correct. However, you need to uninstall the current `build-gradle` you have installed. You can do this in the package manager inside the Atom UI.

**Comment by noseglid** [comment]
I'll merge and release this. Let me know if you experience any issues with it.

**Comment by chefhoobajoob** [comment]
Will do - thanks!

**Comment by qiyue49** [comment]
run gradle wrapper    
and 

task wrapper(type: Wrapper) {
    gradleVersion = '3.1'
} 

in the build.gradle file
